### ISSUE TITLE
DSC documentation in PowerShell 6

### ISSUE THREAD

**Issue by doctordns** [PowerShell/PowerShell-Docs#3122]
Issue Details
-----------------
In PowerShell-Docs/reference/6/PSDesiredStateConfiguration, there are three documents that describe a part of the DSC infrastructure.  

It is my understanding that, at present, DSC is unsupported in PowerShell 6. FWIW: Get-DSCResource does not work in PowerShell 6.1. 

Should these three documents be removed (at least until such time that DSC support exists in PowerShell 6 or beyond?

Version(s) of document impacted
------------------------------
- [x] Impacts 6.next document
- [x] Impacts 6 document
- [ ] Impacts 5.1 document
- [ ] Impacts 5.0 document
- [ ] Impacts 4.0 document
- [ ] Impacts 3.0 document

Reason(s) for not selecting all version of documents
----------------------------------------------------
- [X] The documented feature was removed in the selected version of PowerShell
- [ ] This issue only shows up in the selected version of the document

**Comment by sdwheeler** [comment]
@mgreenegit @joeyaiello We need a statement we can publish about this.

**Comment by mgreenegit** [comment]
@joeyaiello @SteveL-MSFT 

Confirmed the issue.  Repro:

PS> $psversiontable

Name                           Value
----                           -----
PSVersion                      6.2.0-preview.1
PSEdition                      Core
GitCommitId                    6.2.0-preview.1
OS                             Microsoft Windows 10.0.18277
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


PS> get-dscresource
New-Object : Cannot find type [Microsoft.PowerShell.DesiredStateConfiguration.DscResourceInfo]: verify that the assembly containing this type is loaded.
At C:\program files\powershell\6-preview\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:4056 char:17
+ ... $resource = New-Object -TypeName Microsoft.PowerShell.DesiredStateCon ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidType: (:) [New-Object], PSArgumentException
+ FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.NewObjectCommand

**Comment by SteveL-MSFT** [comment]
@mgreenegit that is https://github.com/PowerShell/PowerShell/issues/2902, I've asked @nitinbps to look at it

**Comment by sdwheeler** [comment]
This is a duplicate of a product bug.

**Comment by doctordns** [comment]
I think you missed the point.
This issue asks for the DSC DOCUMENTATION to be removed from PSH 6 docs (at least until DSC is implemented in PWSH). Yes, the cmdlet is broken - which may be a product bug, but that has nought to do with the documentation.
Unless I am wrong (and DSC _IS_ supported), this issue is still an issue.

**Comment by doctordns** [comment]
I think folks are missing the point. The error in get-dscresource is NOT the error I am referencing here. The issue I raised is about the _DSC Documentation_ being in the PWSH 6 doc set. Yet, get-dscresource is broken (and the product bug you mention is indeed an indication that, so far, DSC is not supported in 6.x). 

The issue is about the DSC documentation and is still an issue, the 'other' product bug is not relevant here. 

Please re-open this issue.

**Comment by sdwheeler** [comment]
@mgreenegit Can you comment on this issue?
